### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by moneyrolling** [louis-gg/chanzhongshuochan#1]
您好，我对你的project（缠中说禅） 很感兴趣，想合作，能联系 admin@moneyrolling.top
谢谢！

**Comment by lanyucomputer** [comment]
运行提示kline_merge is less
fx is less then 2
hk00272 <class 'Exception'> Invalid \uXXXX escape: line 1 column 21687 (char 21686)
fx is less then 2
K线太少？？

**Comment by louis-gg** [comment]
这个是分型太少了。
相当于K太少，导致分型太少。
K线少，有两个可能的原因：
1、数据获取的问题，建议使用聚宽或者PYTDX。pytdx有时候获取有问题，二次获取就好了。
2、实际就是K线太少。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月8日(周二) 下午5:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [louis-gg/chanzhongshuochan] 您好 (#1)




 
运行提示kline_merge is less
 fx is less then 2
 hk00272 <class 'Exception'&gt; Invalid \uXXXX escape: line 1 column 21687 (char 21686)
 fx is less then 2
 K线太少？？

**Comment by louis-gg** [comment]
> 您好，我对你的project（缠中说禅） 很感兴趣，想合作，能联系 [admin@moneyrolling.top](mailto:admin@moneyrolling.top)
> 谢谢！
有好的思路可以给我邮箱，我觉得可以的话，我会实现分享提供给你的。465954457@qq.com
